server:
  port: 8081
spring:
  application:
    name: study
  ##  spring redis config
  redis:
    host: 10.23.3.23
    port: 6379
  #    启动缓存
  ## database config
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://10.23.3.23:5432/postgres
    username: postgres
    password: hik12345+
  jpa:
    properties:
      hibernate:
        hbm2ddl:
          auto: update
        temp:
          use_jdbc_metadata_defaults: false
        dialect: org.hibernate.dialect.PostgreSQLDialect
    show-sql: true
  ##### kafka config
  kafka:
    bootstrap-servers:  10.23.3.23:9092
    consumer:
      group-id: group_study
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
      acks: all
      retries: 3
  #### elasticsearch config  #######
  data:
    elasticsearch:
      cluster-name:  elasticsearch-cluster
      cluster-nodes: 10.23.3.23:9300
  elasticsearch:
    rest:
      uris: 10.23.3.23:9200